#!/bin/bash
echo "Enter  a"
read a
echo "Enter b"
read b
echo "Enter c"
read c
if [ $a -ne $b ] && [ $b -ne $c ] && [ $c -ne $a ]
then
echo "Scalene"
elif [ $a -eq $b ] && [ $b -eq $c ]
then 
echo "Equilateral"
else
echo "Isosceles"
fi




